# Boolean Indexing 
#### Boolean indexing = Filtering in a numpy array using boolean and logical operators
##### ⭐ Step 1 → Normal array
##### ⭐ Step 2 → Condition lagao
##### ⭐ Step 3 → Use condition on array

In [9]:
import numpy as np

##step 1
arr = np.array([10, 25, 30, 5, 80]) 

print(arr)

#step 2 
print(arr>20) #T/F Array
# arr>20

#Step 3 
print(arr[arr>20]) #Array of elements greater than 20

[10 25 30  5 80]
[False  True  True False  True]
[25 30 80]


# ⭐ Example 2: find even numbers

In [10]:
arr =np.arange(1,20)
print(arr[arr%2 == 0]) #array of even numbers 

[ 2  4  6  8 10 12 14 16 18]


# ⭐ Example 3: greater than 50

In [12]:
arr = np.array([20,55,10,99,77])
arr[arr>50] #print(arr[arr>50]) more efficient 

array([55, 99, 77])

# ⭐ Logical AND / OR
#### 1. AND: &

In [16]:
arr = np.array([20,55,10,99,77])
print(arr[(arr>10) & (arr<70)]) #array of elements greater than 10 and less than 70

[20 55]


#### 2.OR: |

In [19]:
arr = np.array([20,55,10,99,77])
print(arr[(arr>10) | (arr%2 == 0)]) #Array of elements greater than or completely divided by 2

[20 55 10 99 77]


# ⭐ Negation (NOT) — ~

In [23]:
arr = np.array([20,55,10,99,77,5,4])
print(arr[~(arr>20)])
arr[~(arr > 20)]

[20 10  5  4]


array([20, 10,  5,  4])

# ⭐ Special Example (important)

In [28]:
arr = np.array([10,20,30,40])
print("Mean: ", np.mean(arr))
arr[arr>np.mean(arr)] #Array of elements greater than mean 

Mean:  25.0


array([30, 40])

# ⭐ Quick practice (do this):
### arr = [5,10,15,20,25,30,35]
#### 1️⃣ arr[arr > 15] = ?
#### 2️⃣ arr[arr % 2 == 1] = ?
#### 3️⃣ arr[(arr >= 10) & (arr <= 30)] = ?
#### 4️⃣ arr[(arr < 10) | (arr > 30)] = ?

In [47]:
arr = np.array([5,10,15,20,25,30,35])

#1️⃣ arr[arr > 15] = ?
print("First Question Answer: ",arr[arr>15]," i,e Elements greater than 15" )

#2️⃣ arr[arr % 2 == 1] = ?
print("Second Question Answer: ",arr[arr%2 == 1]," i,e Elements that are not completely divisible by 2") #Array of odd elements 

#3️⃣ arr[(arr >= 10) & (arr <= 30)] = ?
print("Third Question Answer: ",arr[(arr>= 10) & (arr<=30)]," i,e range of numbers between 10 and 30" ) #Logical AND operator is used

#4️⃣ arr[(arr < 10) | (arr > 30)] = ?
print("Fourth Question Answer: ",arr[(arr<10) | (arr>30)]," i,e Elements that are either less than 10 or greater than 30" )

#BONUS POINT
print("Elements that are not less than 20: ",arr[~(arr<20)])

First Question Answer:  [20 25 30 35]  i,e Elements greater than 15
Second Question Answer:  [ 5 15 25 35]  i,e Elements that are not completely divisible by 2
Third Question Answer:  [10 15 20 25 30]  i,e range of numbers between 10 and 30
Fourth Question Answer:  [ 5 35]  i,e Elements that are either less than 10 or greater than 30
Elements that are not less than 20:  [20 25 30 35]
