# ⭐ Concept 1: Basic Indexing (1D Array)
##### Indexing starts from 0
### 1D array indexing 

In [60]:
import numpy as np 
arr = np. array([1,2,3,4,5])
print("Element at index 2 is: ", arr[2])

Element at index 2 is:  3


### 2D indexing 
### arr[row_index, column_index]

In [18]:
arr = np.array([
    [1,2],[3,4]
])
print(arr)
print("diemnsions: ", arr.ndim)
print(arr.shape)
print("Element at index[0,0](row no. 0, col no. 0) is : ",arr[0,0])
print("Element at index[0,1](row no. 0, col no. 1) is : ",arr[0,1])
print("Element at index[1,0](row no. 1, col no. 0) is : ",arr[1,0])
print("Element at index[1,1](row no. 0, col no. 0 is : ",arr[1,1])
               

[[1 2]
 [3 4]]
diemnsions:  2
(2, 2)
Element at index[0,0](row no. 0, col no. 0) is :  1
Element at index[0,1](row no. 0, col no. 1) is :  2
Element at index[1,0](row no. 1, col no. 0) is :  3
Element at index[1,1](row no. 0, col no. 0 is :  4


# ⭐ Concept 2: Slicing (1D Array)
### Slicing = “Extract part of the array.”
### Formula: arr[start : stop : step]
#### start → starting point-->(inclusive)
#### stop → end point --> (exclusive)
#### step → Gap
## 1D Array Slicing

In [28]:
arr = np.array([10,20,30,40,50,60])
print(arr)
print("Slice1: ", arr[1:3]) #[20,30]
print("Slice2: ", arr[:4]) #[10,20,30,40]-->start is index 0 by default 
print("Slice3: ", arr[3:]) #[40,50,60]-->endby is default the ending element of the array
print("Slice4: ", arr[::]) #slice whole array
print("Slice5: ", arr[::-1]) #Slice in reverse order
print("Sice6: ", arr[0:4:2]) #step/gap = 2-->skip one element after another 

[10 20 30 40 50 60]
Slice1:  [20 30]
Slice2:  [10 20 30 40]
Slice3:  [40 50 60]
Slice4:  [10 20 30 40 50 60]
Slice5:  [60 50 40 30 20 10]
Sice6:  [10 30]


# ⭐ Concept 3: 2D Slicing
#### 2D slicing = “Slice chunk of a matrix”.
#### Formula: arr[row_start : row_end , col_start : col_end]

In [57]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [0,1,2]
])
print(arr)
print("Size: ", arr.size)
print("Dimensions: ", arr.ndim)
print("Shape: ",arr.shape)

print("\n\n")
print(arr[0:3 ,0:3]) #[[1,2],[4,5]]
print("\n\n")
print(arr[1:3 ,1:3]) 
print("\n\n")
print(arr[2:,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]]
Size:  12
Dimensions:  2
Shape:  (4, 3)



[[1 2 3]
 [4 5 6]
 [7 8 9]]



[[5 6]
 [8 9]]



[[7 8]
 [0 1]]


In [59]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Q:-> [[1,2,3],
#      [4,5,6],
#      [7,8,9]]

#### 1️⃣ arr[1:, 1:] = ?
#### 2️⃣ arr[:2, 1:] = ?
#### 3️⃣ arr[0:3, 0:1] = ? (Only first column)
#### 4️⃣ arr[1, :2] = ?
#### 5️⃣ arr[:, ::2] = ? (Every 2nd column)