# ⭐ Next: Concept – Axis (axis=0, axis=1)

Axis basically batata hai ki operation row pe apply ho, ya column pe.

axis = 0 ➜ down the rows

Combine vertically
(operate column-wise)

axis = 1 ➜ across the columns

Combine horizontally
(operate row-wise)

Example:mple:

In [6]:
import numpy as np 
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

print("Sum along column (axis = 0): ",arr.sum(axis = 0))

print("Sum along rows (axis = 1): ", arr.sum(axis = 1))

[[1 2 3]
 [4 5 6]]
Sum along column (axis = 0):  [5 7 9]
Sum along rows (axis = 1):  [ 6 15]


# ⭐ Next: try these (super important)

Given:

In [16]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Mean:-->col wise ", arr.mean(axis = 0))
print("Min element col wise: ",arr.min(axis=0))
print("Max element col wise: ",arr.max(axis=0))

print("Mean:-->Row wise ",arr.mean(axis=1))
print("Min element row wise: ",arr.min(axis=1))
print("Max element row wise: ",arr.max(axis=1))


Mean:-->col wise  [2.5 3.5 4.5]
Min element col wise:  [1 2 3]
Max element col wise:  [4 5 6]
Mean:-->Row wise  [2. 5.]
Min element row wise:  [1 4]
Max element row wise:  [3 6]


# ⭐ Next: Practice 1 (easy)

Given:

In [21]:
arr = np.array([[2,4,6],
                [1,3,5],
                [7,8,9]])
print(arr)

print("Col wise mean: ", arr.mean(axis = 0))
print("row wise mean: ", arr.mean(axis = 1))

print("Max element col wise: ", arr.max(axis = 0))
print("Min element row wise: ", arr.min(axis = 0))

[[2 4 6]
 [1 3 5]
 [7 8 9]]
Col wise mean:  [3.33333333 5.         6.66666667]
row wise mean:  [4. 3. 8.]
Max element col wise:  [7 8 9]
Min element row wise:  [1 3 5]
