# ⭐ Broadcasting & Vectorized Operations
### 💡 Broadcasting
Broadcasting matlab:

Jab NumPy different shape ke arrays ko ek sath calculation karwata hai automatically adjust karke

Broadcasting tab chalta hai jab shapes match ho jaye ya automatically expand ho sake

#### Broadcasting tab hoti hai jab:
same OR 1


✔ 1. Size is same

OR

✔ 2. One of them is 1


#### No broadcasting jab:
different AND both > 1

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print("Array without broadcasting: ",arr)
arr = arr+5 #Broadcasting
print("Array after broadcasting: ",arr) #-->[1+5,2+5,3+5,4+5,5+5]-->[6,7,8,9,10]

Array without broadcasting:  [1 2 3 4 5]
Array after broadcasting:  [ 6  7  8  9 10]


### ⭐ Vectorized operations
Means:

operations element-by-element perform hote hain bina loops likhe

In [4]:
print("Vectorized array: ",arr*5)

Vectorized array:  [30 35 40 45 50]


# ⭐ Array + Array operation

In [8]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,0])
c = a+b  #Simple addition, element-wise.
print(c)
print(type(c))

[ 7  9 11 13  5]
<class 'numpy.ndarray'>


# ⭐ Mini practice (answer now)
#### TRY:
##### arr = np.array([2,4,6])
##### print(arr + 3 ) = ?
##### print(arr * 2 ) = ?
##### print(arr - 1 ) = ?
##### print(arr** 2)** 2)

In [13]:
arr = np.array([2,4,6])

#1. print(arr + 3 ) = ?
print("Question 1: ",arr+3)

#2 print(arr * 2 ) = ?
print("Question 2: ",arr*2)

#3. print(arr - 1 ) = ?
print("Question 3: ",arr-1)

#4. print(arr** 2)
print("Question 4: ",arr**2)

Question 1:  [5 7 9]
Question 2:  [ 4  8 12]
Question 3:  [1 3 5]
Question 4:  [ 4 16 36]


# ⭐ Next Concept (important)

Ab aate hain Broadcasting Rules par.

Broadcasting tab chalta hai jab shapes match ho jaye ya automatically expand ho sake.

Example:

In [17]:
a = np.array([1,2,3]) #1D Array
b = np.array([[10],[20],[30]]) #2D Array
print(a+b) #Result will aslo be a 2D array

[[11 12 13]
 [21 22 23]
 [31 32 33]]


Array vertical expand ho gaya
aur a horizontally.

Isi magic ko broadcasting dimension matching kehte hain.

In [18]:
a = np.array([1,2,3])
b = np.array([[10,20,30]])

print(a + b)

[[11 22 33]]


# Incorrect Broadcasting 
shape of a -->(1,3)
shape of b --> (1,2)-->it should be either 1,1 or 1,3

In [21]:
a = np.array([[1,2,3]])
b = np.array([[10,20]])

print(a.shape)
print(b.shape)

print(a + b) #it will throq an error

(1, 3)
(1, 2)


ValueError: operands could not be broadcast together with shapes (1,3) (1,2) 

# SHORT NOTE

#### CASE 1

a.shape = (1,3)

b.shape = (1,1)

##### CHECK:

(1 == 1)  ✔

(3 != 1)  BUT b has 1 → so O

#### CASE 2

a.shape = (2,3)

b.shape = (2,1

##### CHECK:

(2 == 2) ✔

(3 != 1) but b has 1 → O

#### CASE 3

a.shape = (1,3)

b.shape = (1,2

##### CHECK:

(1 == 1)   ✔
### ERROR
(3 != 2)   ❌ and NONE is 1 → ERROR)K)K)

# SHORT NOTE 2
#### CASE 1

a.shape = (5,1)

b.shape = (1,3

##### CHECK:

5 vs 1  → b has 1 → OK

1 vs 3  → a has 1 → OK)