# Introduction to Numpy
#### NumPy = Numerical Python
#### means:  maths / stats / machine learning ka engine for python

###  Why NumPy?

#### Plain Python list = slow… 
#### NumPy array = fast… 

### Reason:

####  Contiguous Memory

#### Vectorized Operations

#### Performs operations with the speed of C language 

In [1]:
import numpy as np
print("Numpy Version: ", np.__version__)

Numpy Version:  1.26.4


# 0D Array (zero dimensions)

In [11]:
arr = np.array(10)
print(arr)
print(type(arr))
print(arr.ndim)
print(np.shape(arr))

10
<class 'numpy.ndarray'>
0
()


# Attributes 
##### Array attributes are built-in properties of NumPy arrays that provide information about an array’s structure, such as its dimensions, shape, size, and data type.
#### arr.ndim → number of dimensions

#### np.shape() → number of rows & columns

#### np.size() → total number of elements

#### arr.dtype → data type of each element

# 1D array

In [13]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)
print(np.shape(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)


# 2D Arrays

In [28]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print("Numpy array: ",arr)
print("Type of the array: ",type(arr))
print("Dimensions: ",arr.ndim)
print("Shape: ",np.shape(arr)) 
print("Size: ",np.size(arr))
print("Data Type: ",arr.dtype)

Numpy array:  [[1 2 3 4 5]
 [6 7 8 9 0]]
Type of the array:  <class 'numpy.ndarray'>
Dimensions:  2
Shape:  (2, 5)
Size:  10
Data Type:  int32


#### ndim-->dimensions 
#### np.Shape() gives the number of rows and columns in an array 
#### np.size() --> number of elements
#### arr.dtype -->gives datatype-->int32

# 3D Arrays

In [40]:
arr = np.array([[[1,2,3],[4,5,6]], #Block 1
               [[7,8,9],[1,2,3]], #Block 2
               [[4,5,6],[7,8,9]], #Brock 3
               ]) # 3Blocks of 2 rows of each and 3 columns
print("Array: ",arr)
print("Dimensions: ",arr.ndim)
print("Shape: ",np.shape(arr))
print("Datatype: ",arr.dtype)

Array:  [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]

 [[4 5 6]
  [7 8 9]]]
Dimensions:  3
Shape:  (3, 2, 3)
Datatype:  int32


# Predefined arrays 
##### Predefined arrays in NumPy are special arrays that are created automatically with fixed values such as zeros, ones, identity matrices, or a constant value.They save time and help in quickly initializing data structures without writing values manually.
## 1. Array of zeros → creates an array filled with 0

In [49]:
arr = np.zeros((3,3))
print(arr)
print("Dimensions: ",arr.ndim)
print("Shape: ",np.shape(arr))
print("Data Type: ",arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Dimensions:  2
Shape:  (3, 3)
Data Type:  float64
Datatype:  float64


## 2. Array of ones (1) → creates an array filled with 1

In [50]:
arr = np.ones((3,4))
print("Array: ",arr)
print("Datatype: ",arr.dtype)
print("Shape: ", np.shape(arr))
print("Dimensions: ", arr.ndim)
print("Datatype: ",arr.dtype)

Array:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Datatype:  float64
Shape:  (3, 4)
Dimensions:  2
Datatype:  float64


# 3. np.full((2,2),7) → creates an array filled with a specific constant

In [55]:
arr = np.full((2,2),7)
print("Array: ",arr)
print("Datatype: ",arr.dtype)
print("Shape: ",np.shape(arr))
print("Size/ No. of elements: ", np.size(arr))
print("Dimensions: ", arr.ndim)

Array:  [[7 7]
 [7 7]]
Datatype:  int32
Shape:  (2, 2)
Size/ No. of elements:  4
Dimensions:  2


 # 4. Identity matrix/ array np.eye() → creates an identity matrix

In [65]:
arr = np .eye(4)
print("Array: ",arr)
print("Datatype: ",arr.dtype)
print("Size: ", np.size(arr))
print("shape: ",np.shape(arr))
print("Dimensions: ", arr.ndim)

Array:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Datatype:  float64
Size:  16
shape:  (4, 4)
Dimensions:  2


# RANGE ARRAYS
##### Range arrays are NumPy arrays created by generating a sequence of numbers within a specified range, either with fixed steps or equal spacing.They are used to create numeric sequences without manually typing each value.
### Two main functions:
## 1. np.arange() → sequence with step value

In [84]:
arr = np.arange(1,10)
print(arr)
arr2 = np.arange(10,20,2)
print(arr2)
print("Datatype: ", arr.dtype)

[1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]
Datatype:  int32


## 2. np.linspace() → sequence with equal spacing

In [69]:
arr = np.linspace(0, 1, 5) 
print(arr)

[0.   0.25 0.5  0.75 1.  ]


# QUESTIONS 
## 1️⃣ Create a 1D array from 1 to 20

In [74]:
arr = np.arange(1,20,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## 2️⃣ Create a 3×3 identity matrix

In [76]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 3️⃣ Use arange() to create even numbers from 2 to 50

In [78]:
arr = np.arange(2,50,2)
print("Even numbers are: ",arr)

Even numbers are:  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


## 4️⃣ Check shape, ndim, size of a 4×4 matrix

In [83]:
arr = np.zeros((4,4))
print(arr)
print("Shape: ", np.shape(arr))
print("Dimensions: ",arr.ndim)
print("Size: ",np.size(arr))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape:  (4, 4)
Dimensions:  2
Size:  16


## 5️⃣ Convert an integer array to float

In [91]:
arr = np. arange(1,10)
print("Array before converting to float: ", arr)
print("Datatype of array: ", arr.dtype)
arr = arr.astype((float))
print("Array after converting to float: ", arr)
print("Datatype of array: ", arr.dtype)


Array before converting to float:  [1 2 3 4 5 6 7 8 9]
Datatype of array:  int32
Array after converting to float:  [1. 2. 3. 4. 5. 6. 7. 8. 9.]
Datatype of array:  float64
